- README.md
Hai!
Saya baru saja merubah repo ini ke Markdown syntax. Karena akan lebih mudah untuk berkontribusi dan memasukkan daftar baru.
Repositori ini juga kekurangan beberapa hal yaitu:
- Lisensi.
- Pedoman Kontributor.
- Kode etik.
Untuk informasi lebih lanjut, silahkan lihat contoh daftar-daftar yang ada di dalam repositori [sindresorhus/awesome](https://github.com/sindresorhus/awesome). Jika sudah menemukan contoh yang bagus, silahkan di terapkan. :smile: 
Hal lainnya:
> Jika ada yang ingin ditambahkan atau dikoreksi bisa PM ke Facebook saya Fariz Ramadhan ya! :)
Hatur Nuhun. :)
GitHub mempunyai fitur _Isu_, daripada melakukan PM ke Anda pribadi, lebih baiknya memakai fitur Isu ini untuk diskusi lebih lanjut dan di masa mendatang akan lebih banyak kontributor yang dapat bergabung. …
> Mengubah ke Markdown syntax

- LICENSE
- README-EN.md
- README.md
Lisensi dirubah dikarenakan repositori ini bukan berisi _software_ namun berisi daftar. Sehingga lebih baik menggunakan lisensi lain yang tidak mengacu secara khusus pada _software_. Readme juga ditambahkan versi bahasa Inggris. Jika ada saran perubahan, boleh ditambahkan.
Terima kasih.
> Update License, Update Readme and Added English Translation

- README.md
Memudahkan navigasi dengan daftar isi dan kategori, yang bahasa Inggris belum. Ditambah kolom mengenai akses API dan juga penambahan beberapa API.
> Update README.md with category

- README-EN.md
- README.md
Update english translation and small changes in README.md
> Update English Translation

- README.md
API Kode Pos kalarau sudah tidak aktif. 
Ada tambahan API Kode Pos baru.
> Update API Kode Pos

- README.md
Adding BPS web API into the list.
> Adding BPS web API into the list

- README.md
> Adding BMKG data source.

- README.md
Berikut beberapa endpoint yang disediakan:
- Data Indonesia
- Data Indonesia Berdasarkan Provinsi
- Global Data
- Global Data (Positif)
- Global Data (Sembuh)
- Global Data (Meninggal)
> Menambahkan api data kesehatan

- README.md
dokumentasi api ada di https://github.com/mathdroid/covid-19-api
> add api covid19 from mathdroid

- README.md
add OVO unofficial API by lintangtimur..
> add OVO unofficial API by lintangtimur

- README.md
mendapatkan pertanyaan dan jawaban dari id.quora.com
> rest api quora indonesia

- README.md
penambahan dan pengubahan status kawalcovid yang tidak aktif
> penambahan api rumah sakit rujukan, kasus perprovinsi dan lainnya

- README.md
> Penambahan API Deezer

- README.md
mas saya tambah kategori buku dan API alquran ini.
> Add kategori buku dan API Alquran

- README.md
Saya menambahkan API saya sendiri. Dapat dilihat di https://github.com/Reynadi531/api-covid19-indonesia-v2
> Tambah API Kesehatan

- README.md
Saya tambahkan beberapa API berikut ini:
| Nama API  | Developer | URL | Status  | Deskripsi | `Auth` |
| --------------- |:---------:|:---:|:-------:|:----------|:------:|
| Quran JSON | penggguna | [Link](https://github.com/penggguna/QuranJSON) | `Aktif` | Quran JSON (Terjemahan Indonesia, Tafsir, dan Audio) | Tidak |
| Duitku | Duitku | [Link](https://docs.duitku.com) | `Aktif` | Payment Gateway Indonesia | `apiKey` |
| BCA | BCA | [Link](https://developer.bca.co.id/documentation) | `Aktif` | API Bank BCA | `apiKey` |
| Jadwal Sholat | lakuapik | [Link](https://github.com/lakuapik/jadwalsholatorg) | `Aktif` | Jadwal sholat berdasarkan kota/kabupaten di Indonesia | Tidak |
> Tambah beberapa API

- README-EN.md
- README.md
i found the English translation hasn't been updated, so i try to fix that.
the list i changed:
- thead (deskripsi > description)
- thead (Nama API > API Key)
- thead content `Auth` (Tidak > No)
- sync with API bahasa
- some typo, etc.
> update english translation sync with original (bahasa)

- README.md
Hi, saya menambahkan api cnn indonesia supaya bagi yang ingin membuat website berita dan masih kekurangan konten bisa menggunakan api ini
> add API cnn indonesia

- README.md
hallo , izin share buku resep makanan indonesia
> add a book recipes api

- README-EN.md
- README.md
dengan di host di github, keberadaan API terus berlangsung selama github masih ada
> Tambah API Json yang di hosted di Github

- README.md
Ramalan Cuaca Indonesia ini berbentuk Json, sehingga mudah diimplementasikan di Aplikasi Mobile maupun Website
> Tambah API Ramalan Cuaca Indonesia bersumber dari BMKG

- README-EN.md
- README.md
- Lazada
- Shopee
- J&T (JET)
`Fix typo url Elevenia`
> Penambahan Beberapa API Jasa Pengiriman dan eCommerce

- README.md
Tambah referensi API sosial media; Instagram Media, User Stories, Profile Highlight, Profile Viewer, Twitter Video Source.
> Tambah Referensi API Sosial Media

- README.md
Saya tambahkan karena kelihatannya belum ada 🙂
> Menambahkan API Facebook Video Downloader

- README.md
Menambahkan 2 API kategori Hiburan
> Menambahkan 2 API kategori Hiburan

- README.md
mas ijin nambahin beberapa api yang saya buat, free to use semua. thanks mas!
> + beberapa api

- README.md
Menambahkan ArugaZ API's, hasil saya scrape website. Terimakasih 👍
> Add ArugaZ Api

- README.md
@farizdotid 
tambahan wikipedia api
- mengambil data api wikipedia
- ada dokumentasinya sendiri
- dapat mengambil data yang hanya didukung bahasa indonesia
> wikipedia api

- README.md
Dear @farizdotid 
Perkenalkan saya Vincent dari PT Solusi Inovasi Bisnis. Saya ingin menambahkan [smsnotif.id](https://www.smsnotif.id/) ke dalam daftar. SMSNotif menyediakan API untuk mengirimkan SMS. Selain itu tersedia juga package untuk Laravel [smsnotif/smsnotif](https://packagist.org/packages/smsnotif/smsnotif). 
Semoga API ini dapat membantu teman-teman yang membutuhkan. 
Terima Kasih.
> Menambahkan API SMSNotif.id

- README-EN.md
- README.md
Saya telah menambahkan API untuk mendapatkan informasi mengenai produk-produk investasi legal dan ilegal yang beredar di Indonesia. Sumber data diambil dari OJK dan diperbarui setiap hari.
> docs: Add OJK invest API

- README.md
> docs:the lazy media api

- README-EN.md
- README.md
maaf kang fariz, suluh mau mengganti developer dan url untuk api pencarian kodepos.
hatur nuhun.
> saya mengubah username :)

- README.md
> added API LK21

- README.md
> Menambahkan Bioskop-Api

- README.md
Ganti Versi Min, Yang Dulu Masih Jelek :)
> Mengganti V1 ke V2

- README-EN.md
- README.md
Kalau gak diperlukan, badge-nya boleh dihilangkan😅
> Xendit payment gateway API

- README.md
Halo, saya menambahkan API Al - Quran dengan menerapkan teknik machine learning untuk memudahkan pencarian ayat pada surah, serta menambahkan fitur untuk memudahkan mencari terjemahan dan tafsir
> Menambahkan API Al - Quran

- README.md
Pembaruan nama, link dan deskripsi pada API Lambang daerah seluruh indonesia. Karna sekarang juga dapat menampilkan lambang kabupaten seluruh indonesia
> Update nama, link dan deskripsi API Lambang Daerah Seluruh Indonesia

- README.md
API untuk membuat email sementara
> Menambahkan API Temp Mail

- README.md
- Fix branding name Doku to DOKU
- Added DOKU Jokul documentation link
> Added DOKU Jokul

- README.md
Assalamualaikum bang Fariz saya izin mau berkontribusi di DAFTAR-API-LOKAL-INDONESIA, tujuan saya kedepanya untuk mengshare api-api gratis dan juga menambah ilmu dan pengalaman.
> Buku: Add free API Al-qur'an

- README.md
Menambahkan API Data Sekolah di Indonesia dan Mengedit Deskripsi API Al-qur'an Indonesia
> Add API Data Sekolah and Edit my Description

- README.md
Penambahan API baru yaitu All In One Video Downloader
> Update beberapa link dan penambahan API baru

- README.md
Menambahkan API data pesantren se Indonesia
> Add API Data Pesantren se Indonesia

- README.md
Fitur :
- mencari video berdasarkan keyword
- mendapatkan detailt video dari url youtube
- untuk mendapatkan link stream audio youtube
- untuk mendapatkan link stream video youtube
- untuk mendapatkan lirik didalam videonya
> Penambahan Unofficial API Platform Youtube

- README.md
menambahkan API untuk kunci jawaban tts di bagian readme
> add kunci jawaban tts api

- README-EN.md
- README.md
Saya mengembangkan API untuk menyajikan data publik. Berikut [repository](https://github.com/yogski/indonesia-public-static-api) nya. Saya izin tambahkan di sini, semoga bisa bermanfaat untuk banyak orang. 
Berikut API yang saya tambahkan:
1. API Pahlawan Nasional
2. API Gunung Berapi di Indonesia
Saya tambahkan untuk versi Indonesia dan Inggris.
Salam.
> Menambah API pahlawan nasional & gunung berapi

- README.md
izin menambahkan beberapa api mas
1.Twitter Trends API
2. Currency Exchange API
3. Jadwal Shalat API
4. KBBI API
6. Lirik Lagu
> add: beberapa api

- README.md
Update link , url fdciabdul.tech moved to kitadev.id 👍
> Update link -> move to new link

- README.md
sumber https://github.com/emsifa/api-wilayah-indonesia
> menambahkan API baru di kategori lokasi 

- README.md
Saya telah menambahkan API untuk doa sehari hari dan lain lain. mohon segera di review, terimakasihh.
> menambahkan doa - doa API

- README.md
Menambahkan Quran API ID dan memperbarui nama.
> Tambah Quran API ID

- README.md
Hi @farizdotid
I want to add my API [rs-bed-availability-api](https://github.com/bayungrh/rs-bed-availability-api) to your documentation.
Thanks.
> Add rs-bed-availability-api

- README.md
menghapus website yang mati dan replace dngn yg baru
> renew website

- README.md
1. TokoCrypto Private API
2. Indodax Public API
3. Full Dokumentasi API public/private
> Api Exchange Crypto Indonesia

- README.md
Adding detik news API, search, list, get news detail.
> adding detik news API

- README.md
Add Avamini API. API untuk generate secara dinamis gambar avatar. Hope you consider it.
> Add Avamini API

- README.md
API ini berfungsi untuk mendapatkan quotes anime.
> Add Katanime API

- README.md
penambahan api ramalan cuaca dari weatherapi.com
> Penambahan API Ramalan Cuaca (weatherapi.com)

- README.md
Halo, berikut saya menambahkan unofficial API buku digital dari Gramedia.
> Add Unofficial Gramedia Ebooks API

- README.md
izin Tambah API baru mas untuk deteksi wajah / cek kemiripan wajah
> Add Face API

- README.md
> Ada update api crypto

- README.md
Holy Quran API - 6236 verses, 114 surah, 30 Juz
> Holy Quran API - 6236 verses, 114 surah, 30 Juz

- .github/ISSUE_TEMPLATE/lapor_masalah.md
- .github/ISSUE_TEMPLATE/tambah_api.md
- .github/PULL_REQUEST_TEMPLATE/tambah_api.md
- CODE_OF_CONDUCT.MD
- CONTRIBUTING.MD
- README.md
**Commit Changes**
- [docs: update status of the API](https://github.com/farizdotid/DAFTAR-API-LOKAL-INDONESIA/commit/4c3751bd74622f8c2d10efbcdb7fcfd67bf1d334)
- [docs: add PR & issues template](https://github.com/farizdotid/DAFTAR-API-LOKAL-INDONESIA/commit/2a62641c5b8f41e125cb3874b830b0d9d48cb4d7)
- [docs: add coc & contributing docs](https://github.com/farizdotid/DAFTAR-API-LOKAL-INDONESIA/commit/c07cf2019be4dfe94c8fcd224677fcd1ecf2aebd)
Kindly @farizdotid to check it
> docs: Add basic Community Standards & Update API Status

- README.md
Menambahkan api berita dari media berita jakarta post
> menambahkan api berita

- README.md
**API Name**: Web API PDDIKTI Kemendikbud
**Developer**: Kemendikbud RI
**API Docs**: -
**Status**: Active
**Description**: PDDIKTI Kemendikbud secara sengaja/tidak sengaja membuat API data mahasiswanya dapat diakses secara publik. Hal ini diketahui ketika melakukan inspeksi _network_ pada web (https://pddikti.kemdikbud.go.id) melalui _inspect tool_ piranti lunak peramban Firefox.
> feat: menambahkan api publik data mahasiswa

- README.md
***Nama API***: Blue Archive API 
***Developer***: arufars
***API Docs***: ada
***Status***: Active
***Description***:  Berisi mengenai informasi karakter Students game dari Blue Archive
> add: blue-archive API

- README.md
Untuk mengecek ID Game seperti Mobile Legend, Free Fire dan masih banyak game lainnya full dokumentasi https://docs.topup.monster
> Add api.topup.monster

- README.md
Nama API: Hibersunda
Developer: [https://github.com/hiberin/](url)
Link: [https://hibersunda.netlify.app/](url)
Status: Aktif
Deskripsi: API untuk pencarian kosa kata dalam Undak Usuk BasaSunda
Auth: Tidak
> menambahkan hibersunda

- README.md
> update link source

- README.md
API ini akan diimplementasikan oleh Broker untuk menghubungkan sistem backend mereka ke TradingView.
> add tradingview api

- README.md
Nama API: Random Quotes Generator
Developer: Irfan Akbari Habibi
Status: Aktif
Deskripsi: API untuk Dapatkan Random Quotes Harian 
Auth: Tidak
> Add new API: Random Quotes Generator

- README.md
Tambah API om
Tolong di cek PR nya 
Thanks 🙏
> Tambah API

- README.md
Hi @farizdotid 
I'm yanuar, a product lead from [KiriminAja](https://kiriminaja.com) hopefully we can reach our developer partner by adding the api into this list.
Reach us at https://github.com/kiriminaja
> Add KiriminAja API to the List

- README.md
---
name: Tambah API
about: Tambahkan API kedalam repositori
title: weather-api
labels: api-baru
assignees: @farizdotid 
---
**Nama API**: `weather-api`
**Developer**: [pace11](https://github.com/pace11)
**API Endpoint/Dokumentasi**: [API](https://weather-api-tau-six.vercel.app/) / [Docs](https://weather-api-tau-six.vercel.app/api-docs)
**Status**: `Aktif`
**Deskripsi**: Ramalan Cuaca konversi dari format XML ke JSON sumber dari API BMKG. Sudah tersedia dalam versi Graphql
**Auth**: `Tidak`
Pengguna cukup mengakses melalui [URL](https://weather-api-tau-six.vercel.app/). Untuk melihat dokumentasi lebih detail terkait endpoint yang tersedia bisa melalui Swagger UI [disini](https://weather-api-tau-six.vercel.app/api-docs). Untuk pengguna yang terbiasa menggunakan Graphql, repo ini sudah …
> Add Weather API 

- README-EN.md
- README.md
Menampilkan waktu dan tanggal secara realtime berbasis UNIX
> menambahkan API (TimeAPI)

- README.en.md
- README.md
- data/utilities/en.json
- data/utilities/id.json
Kumpulan api kebutuhan bot, dan beberapa api:  Visitor api, Cek ip api, Cek Website Hidup atau tidak, File api, dan lain-lain dengan respon JSON
> Api Akuari

- data/christian/en.json
- data/christian/id.json
Dear @farizdotid,
Saya telah mengupdate API untuk section christian.
> Update API Akitab

- data/multipurpose/en.json
- data/multipurpose/id.json
Hallo min tolong approve dan merge ,, saya menambahkan akses api gratis
> Akses api gratis

- data/multipurpose/en.json
- data/multipurpose/id.json
- data/utilities/en.json
- data/utilities/id.json
Add serbaguna or multipurpose API
> Tambah API serbaguna

- data/entertainment/en.json
- data/entertainment/id.json
> add new: MyInstants API

- README.en.md
- README.md
- data/books/en.json
- data/books/id.json
Sebelumnya maaf jika ada kesalahan dalam penulisan format untuk data, Saya sebagai pembuat Bukuacak mengucapkan terima kasih.
> Bukuacak (Books)

- data/islamic/en.json
- data/islamic/id.json
> Remove deprecated Jadwal Sholat API by azharimm

- data/islamic/en.json
- data/islamic/id.json
> add new: Qalbun API

- data/education/en.json
- data/education/id.json
Izin nambahin alternatif API KBBI 🙏
> add KBBI API alternative

- data/financial/en.json
- data/financial/id.json
Izin nambah API Logam Mulia / Harga Emas
> Add API : Logam Mulia / Harga Emas
